---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data-nfs-prometheus-rancher-monitoring-prometheus-0
  namespace: cattle-monitoring-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: storage-migration
    app.kubernetes.io/part-of: rancher-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-shared-retain
  volumeName: pvc-e734340c-26bc-4def-a62f-0a2e74822cad
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: am-data-nfs-alertmanager-rancher-monitoring-alertmanager-0
  namespace: cattle-monitoring-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: storage-migration
    app.kubernetes.io/part-of: rancher-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-shared-retain
  volumeName: pvc-eb50ae79-e260-491b-9211-5321c41d7677
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: am-data-nfs-alertmanager-rancher-monitoring-alertmanager-1
  namespace: cattle-monitoring-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: storage-migration
    app.kubernetes.io/part-of: rancher-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-shared-retain
  volumeName: pvc-fc6f7ade-1c27-42ea-86aa-4d79744c73f2
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-monitoring-grafana-nfs
  namespace: cattle-monitoring-system
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: storage-migration
    app.kubernetes.io/part-of: rancher-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-shared-retain
  volumeName: pvc-8a53931a-95dd-4cac-a1b6-8d2fdf1ad15b
  resources:
    requests:
      storage: 2Gi
