---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-write-0
  namespace: cattle-monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: otlp-write
    app.kubernetes.io/part-of: rancher-monitoring
    home-lab.io/project-slug: system
spec:
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-rancher-monitoring-prometheus-0
  ports:
    - name: http
      port: 9090
      targetPort: nginx-http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-write-1
  namespace: cattle-monitoring-system
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: otlp-write
    app.kubernetes.io/part-of: rancher-monitoring
    home-lab.io/project-slug: system
spec:
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-rancher-monitoring-prometheus-1
  ports:
    - name: http
      port: 9090
      targetPort: nginx-http
      protocol: TCP
