---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry-nfs
  namespace: harbor
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: harbor
    home-lab.io/project-slug: applications
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-9910be67-4e50-4e0d-afa9-8beacdfbcb59
  resources:
    requests:
      storage: 50Gi
