---
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: sops-secrets-operator
  labels:
    app.kubernetes.io/name: sops-secrets-operator
    app.kubernetes.io/part-of: sops-secrets-operator
    home-lab.io/project-slug: system
spec:
  defaultNamespace: sops
  dependsOn:
    - name: system-helm-repositories
  labels:
    app.kubernetes.io/name: sops-secrets-operator
    app.kubernetes.io/part-of: sops-secrets-operator
    home-lab.io/project-slug: system
  targets:
    - name: default
      clusterGroup: default
  targetRestrictions:
    - name: default
      clusterGroup: default
  correctDrift:
    enabled: true
    force: true
    keepFailHistory: true
  downstreamResources:
    - kind: ConfigMap
      name: sops-secrets-operator-values
  helm:
    releaseName: sops-secrets-operator
    repo: https://isindir.github.io/sops-secrets-operator/
    chart: sops-secrets-operator
    version: 0.28.0
    timeoutSeconds: 600
    takeOwnership: true
    valuesFrom:
      - configMapKeyRef:
          name: sops-secrets-operator-values
          namespace: fleet-local
          key: values.yaml
    waitForJobs: true
