---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet-local
resources:
  - helmop.yaml
configMapGenerator:
  - name: sops-secrets-operator-values
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: sops-secrets-operator
    app.kubernetes.io/part-of: sops-secrets-operator
    home-lab.io/project-slug: system
configurations:
  - kustomizeconfig.yaml
