---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: devfeed
  namespace: devfeed
  labels:
    app.kubernetes.io/part-of: rancher-monitoring
spec:
  namespaceSelector:
    matchNames:
    - devfeed
  selector:
    matchLabels:
      devfeed-telemetry: 'true'
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 5s
    relabelings:
    - targetLabel: telemetry
      replacement: devfeed-application
    - sourceLabels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_name
      regex: devfeed-(.*)
      targetLabel: service
      replacement: $1
  sampleLimit: 15000
