---
name: wardn-hub
defaultNamespace: wardn
labels:
  app.kubernetes.io/part-of: wardn-hub
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
  - name: postgresql
  - name: postgresql-networkpolicy
  - name: postgresql-pooler-pdb
  - name: valkey
  - name: valkey-networkpolicy
  - name: csi-driver-nfs-helmop
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: wardn-hub-next-build-cache-nfs
      namespace: wardn
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
  timeoutSeconds: 900
  waitForJobs: true
forceSyncGeneration: 36
