---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wardn-hub-next-build-cache-nfs
  namespace: wardn
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: wardn-hub-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: wardn-hub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-c967857e-16b4-40ac-a9d9-af69db0326c7
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wardn-hub-codex-home
  namespace: wardn
  labels:
    app.kubernetes.io/name: wardn-hub-api
    app.kubernetes.io/component: review-automation
    app.kubernetes.io/part-of: wardn-hub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
