---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: jellyfin-apiserver-access
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/name: jellyfin
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
