---
name: jellyfin-helmop
defaultNamespace: fleet-local
paused: false
labels:
  app.kubernetes.io/name: jellyfin
  app.kubernetes.io/part-of: media-stack
  home-lab.io/project-slug: entertainment
dependsOn:
  - name: rancher-project-entertainment
  - name: media-helm-repositories
  - name: media-storage
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: jellyfin-shared-data-nfs
      namespace: media
      jsonPointers:
        - /spec/volumeName
