---
apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  forceSyncGeneration: 16
  defaultNamespace: media
  namespaceLabels:
    app.kubernetes.io/part-of: media-stack
    field.cattle.io/projectId: p-rm645
  namespaceAnnotations:
    field.cattle.io/projectId: local:p-rm645
  dependsOn:
    - name: rancher-project-entertainment
    - name: media-helm-repositories
    - name: media-storage
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
  targets:
    - name: default
      clusterGroup: default
  targetRestrictions:
    - name: default
      clusterGroup: default
  correctDrift:
    enabled: true
    force: true
    keepFailHistory: true
  downstreamResources:
    - kind: ConfigMap
      name: jellyfin-values
  helm:
    releaseName: jellyfin
    repo: oci://oci.trueforge.org/truecharts/jellyfin
    version: 23.5.0
    timeoutSeconds: 1800
    takeOwnership: true
    valuesFrom:
      - configMapKeyRef:
          name: jellyfin-values
          namespace: fleet-local
          key: values.yaml
    waitForJobs: true
