---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-shared-data-nfs
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-33288887-1bce-4adb-8d11-06ca7224e523
  resources:
    requests:
      storage: 20Gi
