---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-shared-data-nfs
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-ce5eb7fc-6c24-422f-9a40-87ea914b2c3b
  resources:
    requests:
      storage: 20Gi
