---
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: harbor
  labels:
    app.kubernetes.io/name: harbor
    app.kubernetes.io/part-of: applications
    home-lab.io/project-slug: applications
spec:
  enabled: true
  url: https://helm.goharbor.io
---
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: openbao
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/part-of: applications
    app.kubernetes.io/component: helm-repository
    home-lab.io/project-slug: applications
spec:
  enabled: true
  url: https://openbao.github.io/openbao-helm
---
apiVersion: catalog.cattle.io/v1
kind: ClusterRepo
metadata:
  name: zitadel
  labels:
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/part-of: applications
    app.kubernetes.io/component: helm-repository
    home-lab.io/project-slug: applications
spec:
  enabled: true
  url: https://charts.zitadel.com
