---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: jellyseerr-config
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-c005090e-a911-4f4a-b7f0-b30a2a7ac30c
  resources:
    requests:
      storage: 128Mi
