---
name: firefly-iii-storage
defaultNamespace: finance
labels:
  app.kubernetes.io/part-of: firefly-iii
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: firefly-iii-upload
      namespace: finance
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
