---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-upload-nfs
  namespace: finance
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: firefly-iii
    app.kubernetes.io/part-of: firefly-iii
    home-lab.io/project-slug: applications
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-0983c6c1-1e0f-4686-bb46-2db6113c300f
  resources:
    requests:
      storage: 256Mi
