---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-fstrim-labeler
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn-fstrim-labeler
    app.kubernetes.io/part-of: longhorn
    home-lab.io/project-slug: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-fstrim-labeler
  labels:
    app.kubernetes.io/name: longhorn-fstrim-labeler
    app.kubernetes.io/part-of: longhorn
    home-lab.io/project-slug: system
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-fstrim-labeler
  labels:
    app.kubernetes.io/name: longhorn-fstrim-labeler
    app.kubernetes.io/part-of: longhorn
    home-lab.io/project-slug: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-fstrim-labeler
subjects:
  - kind: ServiceAccount
    name: longhorn-fstrim-labeler
    namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-fstrim-labeler
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn-fstrim-labeler
    app.kubernetes.io/part-of: longhorn
    home-lab.io/project-slug: system
rules:
  - apiGroups:
      - longhorn.io
    resources:
      - volumes
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-fstrim-labeler
  namespace: longhorn-system
  labels:
    app.kubernetes.io/name: longhorn-fstrim-labeler
    app.kubernetes.io/part-of: longhorn
    home-lab.io/project-slug: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: longhorn-fstrim-labeler
subjects:
  - kind: ServiceAccount
    name: longhorn-fstrim-labeler
    namespace: longhorn-system
