---
name: rancher-compliance-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/name: rancher-compliance
  app.kubernetes.io/part-of: rancher-compliance
  home-lab.io/project-slug: system
dependsOn:
  - name: system-helm-repositories
