---
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - kind: HelmOp
        group: fleet.cattle.io
        version: v1alpha1
        path: spec/downstreamResources/name
      - kind: HelmOp
        group: fleet.cattle.io
        version: v1alpha1
        path: spec/helm/valuesFrom/configMapKeyRef/name
