---
apiVersion: v1
kind: Service
metadata:
  name: wardn-ai-website
  namespace: wardn
  labels:
    app.kubernetes.io/name: wardn-ai-website
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: wardn-ai
spec:
  type: ClusterIP
  trafficDistribution: PreferSameNode
  selector:
    app.kubernetes.io/name: wardn-ai-website
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
