---
name: firefly-iii-data-importer
defaultNamespace: finance
labels:
  app.kubernetes.io/part-of: firefly-iii
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
  - name: firefly-iii
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: firefly-iii-data-importer-config
      namespace: finance
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
