---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-data-importer-config-nfs
  namespace: finance
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: firefly-iii-data-importer
    app.kubernetes.io/part-of: firefly-iii
    home-lab.io/project-slug: applications
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-33b791b0-5718-49bd-927b-5c3d8bc0eedb
  resources:
    requests:
      storage: 256Mi
