---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-data-importer-config
  namespace: finance
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: firefly-iii-data-importer
    app.kubernetes.io/part-of: firefly-iii
    home-lab.io/project-slug: applications
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
