---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-data-importer-config-nfs
  namespace: finance
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: firefly-iii-data-importer
    app.kubernetes.io/part-of: firefly-iii
    home-lab.io/project-slug: applications
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-762e0b32-32ef-479e-b5f9-fd449a0e0850
  resources:
    requests:
      storage: 256Mi
