---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate-default-deny
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: renovate
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress: []
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate-dns-egress
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: renovate
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: renovate
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate-registry-egress
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: renovate
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: renovate
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.0.0.0/8
        - ipBlock:
            cidr: 192.168.3.3/32
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 5000
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: harbor
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - harbor
              - key: component
                operator: In
                values:
                  - core
                  - registry
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 8080
        - protocol: TCP
          port: 5000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: renovate-github-egress
  namespace: renovate
  labels:
    app.kubernetes.io/name: renovate
    app.kubernetes.io/part-of: renovate
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: renovate
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443
