---
name: netbox-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/part-of: netbox
  home-lab.io/project-slug: home-automation
dependsOn:
  - name: rancher-project-home-automation
  - name: home-automation-helm-repositories
