---
name: shipyardhq
defaultNamespace: shipyardhq
labels:
  app.kubernetes.io/part-of: shipyardhq
  home-lab.io/project-slug: applications
rolloutStrategy:
  maxUnavailable: 2
  maxUnavailablePartitions: 2
dependsOn:
  - name: rancher-project-applications
  - name: postgresql
  - name: postgresql-networkpolicy
  - name: postgresql-pooler-pdb
  - name: valkey
  - name: valkey-networkpolicy
helm:
  takeOwnership: true
  timeoutSeconds: 5400
  waitForJobs: true
forceSyncGeneration: 3
