---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shipyardhq-imgproxy
  namespace: shipyardhq
  labels:
    app.kubernetes.io/name: shipyardhq-imgproxy
    app.kubernetes.io/component: image-proxy
    app.kubernetes.io/part-of: shipyardhq
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: shipyardhq-imgproxy
      app.kubernetes.io/component: image-proxy
