---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shipyardhq
  namespace: shipyardhq
  labels:
    app.kubernetes.io/name: shipyardhq
    app.kubernetes.io/part-of: shipyardhq
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: shipyardhq
      app.kubernetes.io/component: web
