---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shipyardhq-next-build-cache-nfs
  namespace: shipyardhq
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: shipyardhq
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: shipyardhq
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-008baac6-af71-42bb-8bcb-43873d3f6aab
  resources:
    requests:
      storage: 8Gi
