---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: k8s-recommendation-engine-apiserver-access
  namespace: cluster-ops
  labels:
    app.kubernetes.io/name: k8s-recommendation-engine
    app.kubernetes.io/part-of: cluster-ops
    home-lab.io/project-slug: home-automation
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: k8s-recommendation-engine
  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "6443"
              protocol: TCP
