---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-recommendation-engine
  namespace: cluster-ops
  labels:
    app.kubernetes.io/name: k8s-recommendation-engine
    app.kubernetes.io/part-of: cluster-ops
    home-lab.io/project-slug: home-automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-ops-k8s-recommendation-engine-readonly
  labels:
    app.kubernetes.io/name: k8s-recommendation-engine
    app.kubernetes.io/part-of: cluster-ops
    home-lab.io/project-slug: home-automation
rules:
  - apiGroups: [""]
    resources:
      - endpoints
      - pods
      - services
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - deployments
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["discovery.k8s.io"]
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /api
      - /api/*
      - /apis
      - /apis/*
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-ops-k8s-recommendation-engine-readonly
  labels:
    app.kubernetes.io/name: k8s-recommendation-engine
    app.kubernetes.io/part-of: cluster-ops
    home-lab.io/project-slug: home-automation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-ops-k8s-recommendation-engine-readonly
subjects:
  - kind: ServiceAccount
    name: k8s-recommendation-engine
    namespace: cluster-ops
