apiVersion: management.cattle.io/v3
kind: Project
metadata:
  name: p-applications
  namespace: local
  labels:
    app.kubernetes.io/name: applications
    app.kubernetes.io/part-of: rancher-projects
spec:
  clusterName: local
  displayName: Applications
  containerDefaultResourceLimit: {}
  namespaceDefaultResourceQuota:
    limit: {}
  resourceQuota:
    limit: {}
