---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo
  namespace: cattle-monitoring-system
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/component: tracing-backend
    app.kubernetes.io/part-of: rancher-monitoring
    home-lab.io/project-slug: system
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - cattle-monitoring-system
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/component: tracing-backend
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 10s
