---
name: personal-blog
defaultNamespace: personal-blog
labels:
  app.kubernetes.io/part-of: personal-blog
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
helm:
  takeOwnership: true
