---
name: cnpg-operator
defaultNamespace: cnpg-system
namespaceLabels:
  app.kubernetes.io/part-of: cnpg-operator
  field.cattle.io/projectId: p-database
namespaceAnnotations:
  field.cattle.io/projectId: local:p-database
labels:
  app.kubernetes.io/part-of: cnpg-operator
  home-lab.io/project-slug: database
imageScans:
  - image: registry.home/ghcr.io/cloudnative-pg/cloudnative-pg
    tagName: cnpg-operator
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=1.0.0 <2.0.0"
dependsOn:
  - name: rancher-project-database
  - name: database-helm-repositories
diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: cnpg-mutating-webhook-configuration
      operations:
        - {"op": "remove", "path": "/webhooks"}
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: cnpg-validating-webhook-configuration
      operations:
        - {"op": "remove", "path": "/webhooks"}
helm:
  releaseName: psql
  chart: ./chart
  valuesFiles:
    - values.yaml
  waitForJobs: true
