---
name: cnpg-operator
defaultNamespace: cnpg-system
labels:
  app.kubernetes.io/part-of: cnpg-operator
  home-lab.io/project-slug: database
dependsOn:
  - name: rancher-project-database
  - name: database-helm-repositories
diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: cnpg-mutating-webhook-configuration
      operations:
        - {"op": "remove", "path": "/webhooks"}
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: cnpg-validating-webhook-configuration
      operations:
        - {"op": "remove", "path": "/webhooks"}
helm:
  releaseName: psql
  chart: ./chart
  takeOwnership: true
  valuesFiles:
    - values.yaml
  waitForJobs: true
