---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: sonarr-values
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: sonarr
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
configurations:
  - kustomizeconfig.yaml
resources:
  - helmop.yaml
