---
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    app.kubernetes.io/part-of: home-dashboard
    field.cattle.io/projectId: p-thbtg
    kubernetes.io/metadata.name: default
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    field.cattle.io/projectId: local:p-thbtg
