---
name: firefly-iii
defaultNamespace: finance
labels:
  app.kubernetes.io/part-of: firefly-iii
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
  - name: firefly-iii-storage
  - name: postgresql
  - name: postgresql-networkpolicy
  - name: postgresql-pooler-pdb
helm:
  takeOwnership: true
