---
name: ups-monitoring
labels:
  app.kubernetes.io/name: ups-monitoring
  app.kubernetes.io/part-of: home-automation
  home-lab.io/project-slug: home-automation
imageScans:
  - image: registry.home/docker.io/library/busybox
    tagName: ups-busybox
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=1.0.0 <2.0.0"
  - image: registry.home/docker.io/instantlinux/nut-upsd
    tagName: nut-upsd
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=2.0.0-0 <3.0.0"
  - image: registry.home/docker.io/brandawg93/peanut
    tagName: peanut
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=6.0.0 <7.0.0"
  - image: registry.home/ghcr.io/druggeri/nut_exporter
    tagName: nut-exporter
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=3.0.0 <4.0.0"
dependsOn:
  - name: rancher-project-home-automation
helm:
  takeOwnership: true
