---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fleet-local
resources:
  - helmops.yaml
configMapGenerator:
  - name: rancher-backup-crd-values
    files:
      - crd-values.yaml
  - name: rancher-backup-values
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: rancher-backup
    app.kubernetes.io/part-of: rancher-backup
    home-lab.io/project-slug: system
configurations:
  - kustomizeconfig.yaml
