---
apiVersion: v1
kind: LimitRange
metadata:
  name: generated-container-defaults
  namespace: postgresql
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: postgresql
    home-lab.io/project-slug: database
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 32Mi
      default:
        memory: 128Mi
