---
name: portfolio
defaultNamespace: portfolio
labels:
  app.kubernetes.io/part-of: portfolio
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
helm:
  takeOwnership: true
