---
name: rack-ops-controllers
defaultNamespace: rack-ops
namespaceLabels:
  app.kubernetes.io/name: rack-ops-controllers
  app.kubernetes.io/part-of: rack-ops
  field.cattle.io/projectId: p-qqtgt
namespaceAnnotations:
  field.cattle.io/projectId: local:p-qqtgt
labels:
  app.kubernetes.io/name: rack-ops-controllers
  app.kubernetes.io/part-of: home-automation
  home-lab.io/project-slug: home-automation
imageScans:
  - image: registry.home/rack-ops/rack-ops
    tagName: rack-ops
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=0.0.0 <1.0.0"
  - image: registry.home/docker.io/library/busybox
    tagName: rack-ops-busybox
    interval: 10m0s
    secretRef:
      name: harbor-registry
    policy:
      semver:
        range: ">=1.0.0 <2.0.0"
dependsOn:
  - name: rancher-project-home-automation
  - name: media-storage
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: rack-ops-state
      namespace: rack-ops
      jsonPointers:
        - /spec/volumeName
