---
name: rack-ops-controllers
defaultNamespace: rack-ops
labels:
  app.kubernetes.io/name: rack-ops-controllers
  app.kubernetes.io/part-of: home-automation
  home-lab.io/project-slug: home-automation
dependsOn:
  - name: rancher-project-home-automation
  - name: media-storage
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: rack-ops-state
      namespace: rack-ops
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
