---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rack-ops-state-nfs
  namespace: rack-ops
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: rack-ops
    app.kubernetes.io/part-of: rack-ops
    home-lab.io/project-slug: home-automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-fcb9cd66-b3cd-458c-a03f-7691cb055ec2
  resources:
    requests:
      storage: 64Mi
