---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rack-ops-state-nfs
  namespace: rack-ops
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: rack-ops
    app.kubernetes.io/part-of: rack-ops
    home-lab.io/project-slug: home-automation
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-a12276a3-9a26-4f7b-8730-e50e821fcfeb
  resources:
    requests:
      storage: 64Mi
