---
name: prowlarr-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/name: prowlarr
  app.kubernetes.io/part-of: media-stack
  home-lab.io/project-slug: entertainment
dependsOn:
  - name: rancher-project-entertainment
  - name: media-helm-repositories
  - name: media-storage
  - name: flaresolverr
