---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.sops.yaml
  - static-seal.sops.yaml
  - helmop.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: openbao-values
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: openbao
    app.kubernetes.io/part-of: openbao
    home-lab.io/project-slug: applications
configurations:
  - kustomizeconfig.yaml
