---
name: home-assistant
labels:
  app.kubernetes.io/name: home-assistant
  app.kubernetes.io/part-of: home-automation
  home-lab.io/project-slug: home-automation
dependsOn:
  - name: rancher-project-home-automation
  - name: home-automation-helm-repositories
helm:
  takeOwnership: true
