---
apiVersion: v1
kind: LimitRange
metadata:
  name: generated-container-defaults
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/part-of: home-automation
    home-lab.io/project-slug: home-automation
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 10m
        memory: 32Mi
      default:
        memory: 256Mi
