---
name: indexly
defaultNamespace: indexly
labels:
  app.kubernetes.io/part-of: indexly
  home-lab.io/project-slug: applications
dependsOn:
  - name: rancher-project-applications
helm:
  takeOwnership: true
