---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: metallb
    app.kubernetes.io/part-of: cluster-networking
    field.cattle.io/projectId: p-zl69x
    home-lab.io/project-slug: system
    kubernetes.io/metadata.name: metallb-system
  annotations:
    field.cattle.io/projectId: local:p-zl69x
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: metallb-helmop
    meta.helm.sh/release-namespace: fleet-local
