---
loadBalancerClass: ""

crds:
  enabled: true

# Layer 2 mode does not need an FRR or FRR-K8s dataplane.
frrk8s:
  enabled: false
speaker:
  frr:
    enabled: false
  priorityClassName: system-node-critical
  tolerations:
    - key: CriticalAddonsOnly
      operator: Equal
      value: "true"
      effect: NoExecute
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 192Mi

controller:
  priorityClassName: system-cluster-critical
  nodeSelector:
    kubernetes.io/arch: arm64
    node-role.kubernetes.io/control-plane: "true"
  tolerations:
    - key: CriticalAddonsOnly
      operator: Equal
      value: "true"
      effect: NoExecute
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 192Mi
