---
apiVersion: v1
kind: Service
metadata:
  name: wardn-license-api
  namespace: wardn
  labels:
    app.kubernetes.io/name: wardn-license-server
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: wardn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wardn-license-server
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: wardn-license-frontend
  namespace: wardn
  labels:
    app.kubernetes.io/name: wardn-license-server
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: wardn
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: wardn-license-server
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
