---
name: valkey-networkpolicy
defaultNamespace: valkey
namespaceLabels:
  app.kubernetes.io/part-of: valkey
  field.cattle.io/projectId: p-database
namespaceAnnotations:
  field.cattle.io/projectId: local:p-database
labels:
  app.kubernetes.io/part-of: valkey
  home-lab.io/project-slug: database
dependsOn:
  - name: valkey
