TZ: Asia/Kolkata
chartContext:
  appUrl: http://flaresolverr.media.svc.cluster.local:8191
image:
  repository: registry.home/ghcr.io/flaresolverr/flaresolverr
  pullPolicy: IfNotPresent
  # renovate: datasource=github-releases depName=FlareSolverr/FlareSolverr
  tag: v3.5.2
imagePullSecret:
  harbor-registry:
    enabled: true
    existingSecret: harbor-registry
global:
  fallbackDefaults:
    storageClass: longhorn
    pvcRetain: true
podOptions:
  defaultAffinity: false
  nodeSelector:
    kubernetes.io/arch: arm64
resources:
  requests:
    cpu: 90m
    memory: 640Mi
  limits:
    cpu: 1000m
    memory: 1536Mi
service:
  main:
    ports:
      main:
        port: 8191
workload:
  main:
    replicas: 1
    podSpec:
      automountServiceAccountToken: false
      labels:
        home-lab.io/topology-group: heavy-media
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              home-lab.io/topology-group: heavy-media
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
      containers:
        main:
          env:
            LOG_LEVEL: info
            LOG_HTML: false
            BROWSER_TIMEOUT: 60000
            TEST_URL: https://www.google.com
persistence:
  config:
    type: emptyDir
    size: 1Gi
networkPolicy:
  ingress:
    enabled: true
    policyType: ingress
    ingress:
      - from:
          - podSelector:
              matchLabels:
                app.kubernetes.io/instance: prowlarr
                app.kubernetes.io/name: prowlarr
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: devfeed
            podSelector:
              matchLabels:
                app.kubernetes.io/name: devfeed-solver-worker
        ports:
          - protocol: TCP
            port: 8191
  egress:
    enabled: true
    policyType: egress
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: kube-system
            podSelector:
              matchLabels:
                k8s-app: kube-dns
        ports:
          - protocol: UDP
            port: 53
          - protocol: TCP
            port: 53
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 0.0.0.0/8
                - 10.0.0.0/8
                - 100.64.0.0/10
                - 127.0.0.0/8
                - 169.254.0.0/16
                - 172.16.0.0/12
                - 192.0.0.0/24
                - 192.0.2.0/24
                - 192.168.0.0/16
                - 198.18.0.0/15
                - 198.51.100.0/24
                - 203.0.113.0/24
                - 224.0.0.0/4
                - 240.0.0.0/4
        ports:
          - protocol: TCP
            port: 80
          - protocol: TCP
            port: 443
