---
name: loki-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/part-of: rancher-monitoring
  home-lab.io/project-slug: system
dependsOn:
  - name: system-helm-repositories
