---
name: loki-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/name: loki
  app.kubernetes.io/part-of: rancher-monitoring
  home-lab.io/project-slug: system
dependsOn:
  - name: system-helm-repositories
  - name: csi-driver-nfs-helmop
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: loki-data-nfs-migration
      namespace: cattle-monitoring-system
      jsonPointers:
        - /spec/volumeName
helm:
  waitForJobs: true
