---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmop.yaml
  - networkpolicy.yaml
  - apiserver-egress-cnp.yaml
configMapGenerator:
  - name: loki-values
    namespace: fleet-local
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: rancher-monitoring
    home-lab.io/project-slug: system
configurations:
  - kustomizeconfig.yaml
