---
name: wardn-ai
defaultNamespace: wardn
labels:
  app.kubernetes.io/part-of: wardn-ai
  home-lab.io/project-slug: applications
correctDrift:
  enabled: false
targetCustomizations:
  - name: local-disable-drift
    clusterName: local
    correctDrift:
      enabled: false
dependsOn:
  - name: rancher-project-applications
  - name: postgresql
  - name: postgresql-networkpolicy
  - name: postgresql-pooler-pdb
  - name: wardn-hub
  - name: csi-driver-nfs-helmop
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: wardn-ai-data-nfs
      namespace: wardn
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
  timeoutSeconds: 900
forceSyncGeneration: 7
