---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wardn-ai-data-nfs
  namespace: wardn
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: wardn-ai
    app.kubernetes.io/part-of: wardn-ai
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-3249098b-7ffc-4a5a-b6d0-a7a6da6ef8dd
  resources:
    requests:
      storage: 5Gi
