---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: valkey-values
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/part-of: valkey
configurations:
  - kustomizeconfig.yaml
resources:
  - grafana-dashboard.yaml
  - registry-secrets.sops.yaml
  - helmop.yaml
