---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-valkey-node-0
  namespace: valkey
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-98113d72-ab80-43b0-a9a9-58c91ac78919
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-valkey-node-1
  namespace: valkey
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-2fcf21b6-ab48-475a-bd36-5359dda76806
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data-valkey-node-2
  namespace: valkey
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-d73d3f41-1725-40f8-978e-55ae183b365f
