---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: music-assistant-home
  namespace: media
  labels:
    app.kubernetes.io/name: music-assistant
    app.kubernetes.io/part-of: media-stack
spec:
  secretName: music-assistant-home-tls
  commonName: music.media.home
  dnsNames:
    - music.media.home
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: home-local-ca
    kind: ClusterIssuer
    group: cert-manager.io
