---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
    home-lab.io/storage-binding: dynamic
  labels:
    app.kubernetes.io/name: music-assistant
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
