---
name: qbittorrent-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/name: qbittorrent
  app.kubernetes.io/part-of: media-stack
  home-lab.io/project-slug: entertainment
  home-lab.io/lockfile-cleanup: enabled
helm:
  takeOwnership: true
