---
name: qbittorrent-helmop
defaultNamespace: fleet-local
labels:
  app.kubernetes.io/name: qbittorrent
  app.kubernetes.io/part-of: media-stack
  home-lab.io/project-slug: entertainment
  home-lab.io/lockfile-cleanup: enabled
dependsOn:
  - name: metallb-config
  - name: rancher-project-entertainment
  - name: media-storage
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: qbittorrent-smart-queues-state-nfs
      namespace: media
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
