---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: qbittorrent-values
    files:
      - values.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
configurations:
  - kustomizeconfig.yaml
resources:
  - secrets.sops.yaml
  - aliases.yaml
  - helmop.yaml
  - smart-queues-apiserver-cnp.yaml
  - smart-queues-controller.yaml
  - smart-queues-grafana-dashboard.yaml
  - smart-queues-monitoring.yaml
  - smart-queues-networkpolicy.yaml
  - smart-queues-prometheusrule.yaml
  - smart-queues-rbac.yaml
  - smart-queues-state-pvc.yaml
  - tracker-refresh-cronjob.yaml
