---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-smart-queues
  namespace: media
  labels:
    app.kubernetes.io/name: qbittorrent-smart-queues
    app.kubernetes.io/component: metrics
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - media
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-smart-queues
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
