---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-smart-queues-state-nfs
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/instance: qbittorrent-smart-queues
    app.kubernetes.io/name: qbittorrent-smart-queues
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-11d5d382-8201-4ed9-9843-d3ecabda328a
  resources:
    requests:
      storage: 64Mi
