---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-smart-queues-state-nfs
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/instance: qbittorrent-smart-queues
    app.kubernetes.io/name: qbittorrent-smart-queues
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-shared-retain
  volumeName: pvc-e3548d56-2677-407f-959c-8586a6e252db
  resources:
    requests:
      storage: 64Mi
