---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dispatcharr-data
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: dispatcharr
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-4ed8cb87-603a-4055-b1f4-42346c48234e
  resources:
    requests:
      storage: 256Mi
