---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: metube-network-boundary
  namespace: media
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: metube
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: traefik
      ports:
        - protocol: TCP
          port: 8081
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.42.0.0/16
              - 10.43.0.0/16
