---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-state
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
