---
apiVersion: v1
kind: Service
metadata:
  name: metube
  namespace: media
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: metube
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
