---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-downloads-nfs-csi
  annotations:
    helm.sh/resource-policy: keep
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  labels:
    app.kubernetes.io/name: media-downloads-nfs-csi
    app.kubernetes.io/part-of: media-stack
spec:
  capacity:
    storage: 3T
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
    - proto=tcp
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.3.115#/nfs/torrents#
    volumeAttributes:
      server: 192.168.3.115
      share: /nfs/torrents
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads-nfs-csi
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: media-downloads-nfs-csi
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-downloads-nfs-csi
  resources:
    requests:
      storage: 3T
