---
name: media-storage
defaultNamespace: media
labels:
  app.kubernetes.io/part-of: media-stack
  home-lab.io/project-slug: entertainment
dependsOn:
  - name: rancher-project-entertainment
helm:
  takeOwnership: true
