---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-unas
  annotations:
    helm.sh/resource-policy: keep
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
  labels:
    app.kubernetes.io/name: media-library-unas
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=3
    - nolock
    - proto=tcp
    - mountproto=tcp
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.1.128#/var/nfs/shared/media#
    volumeAttributes:
      server: 192.168.1.128
      share: /var/nfs/shared/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-unas
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: media-library-unas
    app.kubernetes.io/part-of: media-stack
    home-lab.io/project-slug: entertainment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: media-library-unas
  resources:
    requests:
      storage: 10Ti
