apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-library-nas
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: media-library-nas
    app.kubernetes.io/part-of: media-stack
spec:
  capacity:
    storage: 1Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nas-media
  mountOptions:
    - vers=3
    - nolock
    - proto=tcp
  nfs:
    server: nas.home
    path: /nfs/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library-nas
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: media-library-nas
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nas-media
  volumeName: media-library-nas
  resources:
    requests:
      storage: 1Ti
