---
name: media-ryokan
defaultNamespace: media
labels:
  app.kubernetes.io/part-of: media-stack
  home-lab.io/project-slug: entertainment
dependsOn:
  - name: rancher-project-entertainment
  - name: media-storage
  - name: qbittorrent
  - name: prowlarr
  - name: jellyfin
diff:
  comparePatches:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: ryokan-data
      namespace: media
      jsonPointers:
        - /spec/volumeName
helm:
  takeOwnership: true
