---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ryokan-data
  namespace: media
  annotations:
    helm.sh/resource-policy: keep
  labels:
    app.kubernetes.io/name: ryokan
    app.kubernetes.io/part-of: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pvc-3592d0d7-92fe-47f9-abe6-01fa52c2b71b
  resources:
    requests:
      storage: 128Mi
